[package]
name = "sail_ffi"
edition.workspace = true
version.workspace = true

[build-dependencies]
bindgen = "0.71.0"

[dependencies]
xmas-elf = "0.9.1"
num = "0.4.3"
hex = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
