[package]
name = "boat"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
sail_ffi = { path = "../sail_ffi" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = { workspace = true }
