[package]
name = "boat"
edition.workspace = true
version.workspace = true

[dependencies]
hex = { workspace = true }
clap = { workspace = true }
sail_ffi = { path = "../sail_ffi" }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
